library(tidyverse)
library(tidytext)
library(glue)
library(stringr)

# get a list of the files in the input directory
files<-list.files("/home/sheready/Downloads/speeches")

# stick together the path to the file & 1st file name
fileName<-glue("/home/sheready/Downloads/speeches/", files[1], sep = "")

# get rid of any sneaky trailing spaces
fileName<-trimws(fileName)

# read in the new file
fileText<-glue(read_file(fileName))

# remove any dollar signs (they're special characters in R)
fileText<-gsub("\\$", "",fileText)

# tokenize
tokens<-tibble(text = fileText) %>% unnest_tokens(word, text)
view(tokens)

# get the sentiment from the first text: 
# pull out only sentiment words
# count the # of positive & negative words
# made data wide rather than narrow
# Get count of positive words - count of negative words
tokens %>%
  inner_join(get_sentiments("bing")) %>% 
  count(sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) 

# write a function that takes the name of a file and returns the # of postive
# write a function that takes the name of a file and returns the # of postive
# sentiment words, negative sentiment words, the difference & the normalized difference
GetSentiment<-function(file){
    fileName<-glue("/home/sheready/Downloads/speeches/", file, sep = "")
    fileName<-trimws(fileName)
    fileText<-glue(read_file(fileName))
    fileText<-gsub("\\$", "", fileText) 
    tokens<-data_frame(text = fileText) %>% unnest_tokens(word, text)
    sentiment<-tokens %>%
      inner_join(get_sentiments("bing")) %>% 
      count(sentiment) %>% 
      spread(sentiment, n, fill = 0) %>% 
      mutate(sentiment = positive - negative) %>%
      mutate(file = file) %>% 
      mutate(year = as.numeric(str_match(file, "\\d{4}"))) %>% 
      mutate(president = str_match(file, "(.*?)_")[2]) 
    return(sentiment)
}
GetSentiment(files[1])

# file to put our output in
sentiments <- tibble()

# get the sentiments for each file in our datset
for(i in files){
    sentiments <- rbind(sentiments, GetSentiment(i))
}

# disambiguate Bush Sr. and George W. Bush 
# correct president in applicable rows
bushSr <- sentiments %>% 
  filter(president == "Bush") %>% # get rows where the president is named "Bush"...
  filter(year < 2000) %>% # ...and the year is before 200
  mutate(president = "Bush Sr.") # and change "Bush" to "Bush Sr."

# remove incorrect rows
sentiments <- anti_join(sentiments, sentiments[sentiments$president == "Bush" & sentiments$year < 2000, ])

# add corrected rows to data_frame 
sentiments <- full_join(sentiments, bushSr)

# summerize the sentiment measures
summary(sentiments)

# plot of sentiment over time & automatically choose a method to model the change
ggplot(sentiments, aes(x = as.numeric(year), y = sentiment)) + 
  geom_point(aes(color = president))+geom_smooth(method = "auto")
# add points to our plot, color-coded by president
# pick a method & fit a model

# plot of sentiment by president
ggplot(sentiments, aes(x = president, y = sentiment, color = president)) + 
  geom_boxplot()# draw a boxplot for each president
# is the difference between parties significant?

# get democratic presidents & add party affiliation
democrats <- sentiments %>%
    filter(president == c("Clinton","Obama")) %>%
    mutate(party = "D")

# get democratic presidents & party add affiliation
republicans <- sentiments %>%
    filter(president != "Clinton" & president != "Obama") %>%
    mutate(party = "R")

# join both
byParty <- full_join(democrats, republicans)

# the difference between the parties is significant
t.test(democrats$sentiment, republicans$sentiment)

# plot sentiment by party
ggplot(byParty, aes(x = party, y = sentiment, color = party)) + geom_boxplot() + geom_point()

